name: Build Qt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CMAKE_BUILD_TYPE: Release
  QT_INSTALL_LOCATION: 'C:/Qt'
  QT_VERSION: '6.2.0'
  QT_VC_VERSION: msvc2019_64

jobs:
  build-qt-windows:
    runs-on: windows-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1  # not v2!
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ env.QT_VERSION }}
        dir: ${{ env.QT_INSTALL_LOCATION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Configure CMake
      run: |
        Write-Host ${{ env.QT_INSTALL_LOCATION }}/${{ env.QT_VERSION }}/${{ env.QT_VC_VERSION }}
        cmake -DCMAKE_PREFIX_PATH="${{ env.QT_INSTALL_LOCATION }}/${{ env.QT_VERSION }}/${{ env.QT_VC_VERSION }}" -S ./MorseCode/  -B "${{github.workspace}}/build" -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config $ {{ env.CMAKE_BUILD_TYPE }}

